// Code generated by MockGen. DO NOT EDIT.
// Source: github.com/piresc/nebengjek/services/rides (interfaces: RideGW)

// Package mocks is a generated GoMock package.
package mocks

import (
	context "context"
	reflect "reflect"

	gomock "github.com/golang/mock/gomock"
	models "github.com/piresc/nebengjek/internal/pkg/models"
)

// MockRideGW is a mock of RideGW interface.
type MockRideGW struct {
	ctrl     *gomock.Controller
	recorder *MockRideGWMockRecorder
}

// MockRideGWMockRecorder is the mock recorder for MockRideGW.
type MockRideGWMockRecorder struct {
	mock *MockRideGW
}

// NewMockRideGW creates a new mock instance.
func NewMockRideGW(ctrl *gomock.Controller) *MockRideGW {
	mock := &MockRideGW{ctrl: ctrl}
	mock.recorder = &MockRideGWMockRecorder{mock}
	return mock
}

// EXPECT returns an object that allows the caller to indicate expected use.
func (m *MockRideGW) EXPECT() *MockRideGWMockRecorder {
	return m.recorder
}

// PublishRideCompleted mocks base method.
func (m *MockRideGW) PublishRideCompleted(arg0 context.Context, arg1 models.RideComplete) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "PublishRideCompleted", arg0, arg1)
	ret0, _ := ret[0].(error)
	return ret0
}

// PublishRideCompleted indicates an expected call of PublishRideCompleted.
func (mr *MockRideGWMockRecorder) PublishRideCompleted(arg0, arg1 interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "PublishRideCompleted", reflect.TypeOf((*MockRideGW)(nil).PublishRideCompleted), arg0, arg1)
}

// PublishRidePickup mocks base method.
func (m *MockRideGW) PublishRidePickup(arg0 context.Context, arg1 *models.Ride) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "PublishRidePickup", arg0, arg1)
	ret0, _ := ret[0].(error)
	return ret0
}

// PublishRidePickup indicates an expected call of PublishRidePickup.
func (mr *MockRideGWMockRecorder) PublishRidePickup(arg0, arg1 interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "PublishRidePickup", reflect.TypeOf((*MockRideGW)(nil).PublishRidePickup), arg0, arg1)
}

// PublishRideStarted mocks base method.
func (m *MockRideGW) PublishRideStarted(arg0 context.Context, arg1 *models.Ride) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "PublishRideStarted", arg0, arg1)
	ret0, _ := ret[0].(error)
	return ret0
}

// PublishRideStarted indicates an expected call of PublishRideStarted.
func (mr *MockRideGWMockRecorder) PublishRideStarted(arg0, arg1 interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "PublishRideStarted", reflect.TypeOf((*MockRideGW)(nil).PublishRideStarted), arg0, arg1)
}
