// Code generated by MockGen. DO NOT EDIT.
// Source: ./services/user/gateways.go

// Package mocks is a generated GoMock package.
package mocks

import (
	context "context"
	reflect "reflect"

	gomock "github.com/golang/mock/gomock"
	models "github.com/piresc/nebengjek/internal/pkg/models"
)

// MockUserGW is a mock of UserGW interface.
type MockUserGW struct {
	ctrl     *gomock.Controller
	recorder *MockUserGWMockRecorder
}

// MockUserGWMockRecorder is the mock recorder for MockUserGW.
type MockUserGWMockRecorder struct {
	mock *MockUserGW
}

// NewMockUserGW creates a new mock instance.
func NewMockUserGW(ctrl *gomock.Controller) *MockUserGW {
	mock := &MockUserGW{ctrl: ctrl}
	mock.recorder = &MockUserGWMockRecorder{mock}
	return mock
}

// EXPECT returns an object that allows the caller to indicate expected use.
func (m *MockUserGW) EXPECT() *MockUserGWMockRecorder {
	return m.recorder
}

// MatchAccept mocks base method.
func (m *MockUserGW) MatchAccept(mp *models.MatchProposal) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "MatchAccept", mp)
	ret0, _ := ret[0].(error)
	return ret0
}

// MatchAccept indicates an expected call of MatchAccept.
func (mr *MockUserGWMockRecorder) MatchAccept(mp interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "MatchAccept", reflect.TypeOf((*MockUserGW)(nil).MatchAccept), mp)
}

// PublishBeaconEvent mocks base method.
func (m *MockUserGW) PublishBeaconEvent(ctx context.Context, beaconReq *models.BeaconEvent) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "PublishBeaconEvent", ctx, beaconReq)
	ret0, _ := ret[0].(error)
	return ret0
}

// PublishBeaconEvent indicates an expected call of PublishBeaconEvent.
func (mr *MockUserGWMockRecorder) PublishBeaconEvent(ctx, beaconReq interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "PublishBeaconEvent", reflect.TypeOf((*MockUserGW)(nil).PublishBeaconEvent), ctx, beaconReq)
}

// PublishLocationUpdate mocks base method.
func (m *MockUserGW) PublishLocationUpdate(ctx context.Context, locationEvent *models.LocationUpdate) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "PublishLocationUpdate", ctx, locationEvent)
	ret0, _ := ret[0].(error)
	return ret0
}

// PublishLocationUpdate indicates an expected call of PublishLocationUpdate.
func (mr *MockUserGWMockRecorder) PublishLocationUpdate(ctx, locationEvent interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "PublishLocationUpdate", reflect.TypeOf((*MockUserGW)(nil).PublishLocationUpdate), ctx, locationEvent)
}

// PublishRideArrived mocks base method.
func (m *MockUserGW) PublishRideArrived(ctx context.Context, event *models.RideCompleteEvent) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "PublishRideArrived", ctx, event)
	ret0, _ := ret[0].(error)
	return ret0
}

// PublishRideArrived indicates an expected call of PublishRideArrived.
func (mr *MockUserGWMockRecorder) PublishRideArrived(ctx, event interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "PublishRideArrived", reflect.TypeOf((*MockUserGW)(nil).PublishRideArrived), ctx, event)
}
