// Code generated by MockGen. DO NOT EDIT.
// Source: github.com/piresc/nebengjek/services/users (interfaces: UserGW)

// Package mocks is a generated GoMock package.
package mocks

import (
	context "context"
	reflect "reflect"

	gomock "github.com/golang/mock/gomock"
	models "github.com/piresc/nebengjek/internal/pkg/models"
)

// MockUserGW is a mock of UserGW interface.
type MockUserGW struct {
	ctrl     *gomock.Controller
	recorder *MockUserGWMockRecorder
}

// MockUserGWMockRecorder is the mock recorder for MockUserGW.
type MockUserGWMockRecorder struct {
	mock *MockUserGW
}

// NewMockUserGW creates a new mock instance.
func NewMockUserGW(ctrl *gomock.Controller) *MockUserGW {
	mock := &MockUserGW{ctrl: ctrl}
	mock.recorder = &MockUserGWMockRecorder{mock}
	return mock
}

// EXPECT returns an object that allows the caller to indicate expected use.
func (m *MockUserGW) EXPECT() *MockUserGWMockRecorder {
	return m.recorder
}

// PublishBeaconEvent mocks base method.
func (m *MockUserGW) PublishBeaconEvent(arg0 context.Context, arg1 *models.BeaconEvent) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "PublishBeaconEvent", arg0, arg1)
	ret0, _ := ret[0].(error)
	return ret0
}

// PublishBeaconEvent indicates an expected call of PublishBeaconEvent.
func (mr *MockUserGWMockRecorder) PublishBeaconEvent(arg0, arg1 interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "PublishBeaconEvent", reflect.TypeOf((*MockUserGW)(nil).PublishBeaconEvent), arg0, arg1)
}

// PublishFinderEvent mocks base method.
func (m *MockUserGW) PublishFinderEvent(arg0 context.Context, arg1 *models.FinderEvent) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "PublishFinderEvent", arg0, arg1)
	ret0, _ := ret[0].(error)
	return ret0
}

// PublishFinderEvent indicates an expected call of PublishFinderEvent.
func (mr *MockUserGWMockRecorder) PublishFinderEvent(arg0, arg1 interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "PublishFinderEvent", reflect.TypeOf((*MockUserGW)(nil).PublishFinderEvent), arg0, arg1)
}
