// Code generated by MockGen. DO NOT EDIT.
// Source: ./services/user/repository.go

// Package mocks is a generated GoMock package.
package mocks

import (
	context "context"
	reflect "reflect"

	gomock "github.com/golang/mock/gomock"
	models "github.com/piresc/nebengjek/internal/pkg/models"
)

// MockUserRepo is a mock of UserRepo interface.
type MockUserRepo struct {
	ctrl     *gomock.Controller
	recorder *MockUserRepoMockRecorder
}

// MockUserRepoMockRecorder is the mock recorder for MockUserRepo.
type MockUserRepoMockRecorder struct {
	mock *MockUserRepo
}

// NewMockUserRepo creates a new mock instance.
func NewMockUserRepo(ctrl *gomock.Controller) *MockUserRepo {
	mock := &MockUserRepo{ctrl: ctrl}
	mock.recorder = &MockUserRepoMockRecorder{mock}
	return mock
}

// EXPECT returns an object that allows the caller to indicate expected use.
func (m *MockUserRepo) EXPECT() *MockUserRepoMockRecorder {
	return m.recorder
}

// CreateOTP mocks base method.
func (m *MockUserRepo) CreateOTP(ctx context.Context, otp *models.OTP) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "CreateOTP", ctx, otp)
	ret0, _ := ret[0].(error)
	return ret0
}

// CreateOTP indicates an expected call of CreateOTP.
func (mr *MockUserRepoMockRecorder) CreateOTP(ctx, otp interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "CreateOTP", reflect.TypeOf((*MockUserRepo)(nil).CreateOTP), ctx, otp)
}

// CreateUser mocks base method.
func (m *MockUserRepo) CreateUser(ctx context.Context, user *models.User) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "CreateUser", ctx, user)
	ret0, _ := ret[0].(error)
	return ret0
}

// CreateUser indicates an expected call of CreateUser.
func (mr *MockUserRepoMockRecorder) CreateUser(ctx, user interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "CreateUser", reflect.TypeOf((*MockUserRepo)(nil).CreateUser), ctx, user)
}

// GetOTP mocks base method.
func (m *MockUserRepo) GetOTP(ctx context.Context, msisdn, code string) (*models.OTP, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "GetOTP", ctx, msisdn, code)
	ret0, _ := ret[0].(*models.OTP)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// GetOTP indicates an expected call of GetOTP.
func (mr *MockUserRepoMockRecorder) GetOTP(ctx, msisdn, code interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "GetOTP", reflect.TypeOf((*MockUserRepo)(nil).GetOTP), ctx, msisdn, code)
}

// GetUserByID mocks base method.
func (m *MockUserRepo) GetUserByID(ctx context.Context, id string) (*models.User, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "GetUserByID", ctx, id)
	ret0, _ := ret[0].(*models.User)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// GetUserByID indicates an expected call of GetUserByID.
func (mr *MockUserRepoMockRecorder) GetUserByID(ctx, id interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "GetUserByID", reflect.TypeOf((*MockUserRepo)(nil).GetUserByID), ctx, id)
}

// GetUserByMSISDN mocks base method.
func (m *MockUserRepo) GetUserByMSISDN(ctx context.Context, msisdn string) (*models.User, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "GetUserByMSISDN", ctx, msisdn)
	ret0, _ := ret[0].(*models.User)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// GetUserByMSISDN indicates an expected call of GetUserByMSISDN.
func (mr *MockUserRepoMockRecorder) GetUserByMSISDN(ctx, msisdn interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "GetUserByMSISDN", reflect.TypeOf((*MockUserRepo)(nil).GetUserByMSISDN), ctx, msisdn)
}

// MarkOTPVerified mocks base method.
func (m *MockUserRepo) MarkOTPVerified(ctx context.Context, msisdn, code string) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "MarkOTPVerified", ctx, msisdn, code)
	ret0, _ := ret[0].(error)
	return ret0
}

// MarkOTPVerified indicates an expected call of MarkOTPVerified.
func (mr *MockUserRepoMockRecorder) MarkOTPVerified(ctx, msisdn, code interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "MarkOTPVerified", reflect.TypeOf((*MockUserRepo)(nil).MarkOTPVerified), ctx, msisdn, code)
}

// UpdateToDriver mocks base method.
func (m *MockUserRepo) UpdateToDriver(ctx context.Context, user *models.User) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "UpdateToDriver", ctx, user)
	ret0, _ := ret[0].(error)
	return ret0
}

// UpdateToDriver indicates an expected call of UpdateToDriver.
func (mr *MockUserRepoMockRecorder) UpdateToDriver(ctx, user interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "UpdateToDriver", reflect.TypeOf((*MockUserRepo)(nil).UpdateToDriver), ctx, user)
}
