server:
  address: ":50054"
  rest_port: ":8084"

nsq:
  address: "nsqd:4150"
  lookupd_addresses:
    - "nsqlookupd:4161"

newrelic:
  app_name: "nebengjek-payment-service"
  license_key: "${NEWRELIC_LICENSE_KEY}"

database:
  host: "postgres"
  port: 5432
  name: "payment_db"
  user: "${DB_USER}"
  password: "${DB_PASSWORD}"

payment_gateway:
  api_key: "${PAYMENT_GATEWAY_API_KEY}"
  endpoint: "https://api.payment-gateway.com/v1"
  timeout: 30