// Code generated by MockGen. DO NOT EDIT.
// Source: github.com/piresc/nebengjek/services/gateway (interfaces: GatewayGW)

// Package mocks is a generated GoMock package.
package mocks

import (
	context "context"
	reflect "reflect"

	gomock "github.com/golang/mock/gomock"
	core "github.com/piresc/nebengjek/internal/pkg/models/core"
)

// MockGatewayGW is a mock of GatewayGW interface.
type MockGatewayGW struct {
	ctrl     *gomock.Controller
	recorder *MockGatewayGWMockRecorder
}

// MockGatewayGWMockRecorder is the mock recorder for MockGatewayGW.
type MockGatewayGWMockRecorder struct {
	mock *MockGatewayGW
}

// NewMockGatewayGW creates a new mock instance.
func NewMockGatewayGW(ctrl *gomock.Controller) *MockGatewayGW {
	mock := &MockGatewayGW{ctrl: ctrl}
	mock.recorder = &MockGatewayGWMockRecorder{mock}
	return mock
}

// EXPECT returns an object that allows the caller to indicate expected use.
func (m *MockGatewayGW) EXPECT() *MockGatewayGWMockRecorder {
	return m.recorder
}

// CallLocationService mocks base method.
func (m *MockGatewayGW) CallLocationService(arg0 context.Context, arg1, arg2 string, arg3 interface{}, arg4, arg5 map[string]string) (*core.ProxyResponse, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "CallLocationService", arg0, arg1, arg2, arg3, arg4, arg5)
	ret0, _ := ret[0].(*core.ProxyResponse)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// CallLocationService indicates an expected call of CallLocationService.
func (mr *MockGatewayGWMockRecorder) CallLocationService(arg0, arg1, arg2, arg3, arg4, arg5 interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "CallLocationService", reflect.TypeOf((*MockGatewayGW)(nil).CallLocationService), arg0, arg1, arg2, arg3, arg4, arg5)
}

// CallMatchService mocks base method.
func (m *MockGatewayGW) CallMatchService(arg0 context.Context, arg1, arg2 string, arg3 interface{}, arg4, arg5 map[string]string) (*core.ProxyResponse, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "CallMatchService", arg0, arg1, arg2, arg3, arg4, arg5)
	ret0, _ := ret[0].(*core.ProxyResponse)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// CallMatchService indicates an expected call of CallMatchService.
func (mr *MockGatewayGWMockRecorder) CallMatchService(arg0, arg1, arg2, arg3, arg4, arg5 interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "CallMatchService", reflect.TypeOf((*MockGatewayGW)(nil).CallMatchService), arg0, arg1, arg2, arg3, arg4, arg5)
}

// CallRidesService mocks base method.
func (m *MockGatewayGW) CallRidesService(arg0 context.Context, arg1, arg2 string, arg3 interface{}, arg4, arg5 map[string]string) (*core.ProxyResponse, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "CallRidesService", arg0, arg1, arg2, arg3, arg4, arg5)
	ret0, _ := ret[0].(*core.ProxyResponse)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// CallRidesService indicates an expected call of CallRidesService.
func (mr *MockGatewayGWMockRecorder) CallRidesService(arg0, arg1, arg2, arg3, arg4, arg5 interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "CallRidesService", reflect.TypeOf((*MockGatewayGW)(nil).CallRidesService), arg0, arg1, arg2, arg3, arg4, arg5)
}

// CallUsersService mocks base method.
func (m *MockGatewayGW) CallUsersService(arg0 context.Context, arg1, arg2 string, arg3 interface{}, arg4, arg5 map[string]string) (*core.ProxyResponse, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "CallUsersService", arg0, arg1, arg2, arg3, arg4, arg5)
	ret0, _ := ret[0].(*core.ProxyResponse)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// CallUsersService indicates an expected call of CallUsersService.
func (mr *MockGatewayGWMockRecorder) CallUsersService(arg0, arg1, arg2, arg3, arg4, arg5 interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "CallUsersService", reflect.TypeOf((*MockGatewayGW)(nil).CallUsersService), arg0, arg1, arg2, arg3, arg4, arg5)
}
