// Code generated by MockGen. DO NOT EDIT.
// Source: github.com/piresc/nebengjek/services/gateway (interfaces: GatewayUC)

// Package mocks is a generated GoMock package.
package mocks

import (
	context "context"
	reflect "reflect"

	gomock "github.com/golang/mock/gomock"
	core "github.com/piresc/nebengjek/internal/pkg/models/core"
	location "github.com/piresc/nebengjek/internal/pkg/models/location"
	match "github.com/piresc/nebengjek/internal/pkg/models/match"
	ride "github.com/piresc/nebengjek/internal/pkg/models/ride"
)

// MockGatewayUC is a mock of GatewayUC interface.
type MockGatewayUC struct {
	ctrl     *gomock.Controller
	recorder *MockGatewayUCMockRecorder
}

// MockGatewayUCMockRecorder is the mock recorder for MockGatewayUC.
type MockGatewayUCMockRecorder struct {
	mock *MockGatewayUC
}

// NewMockGatewayUC creates a new mock instance.
func NewMockGatewayUC(ctrl *gomock.Controller) *MockGatewayUC {
	mock := &MockGatewayUC{ctrl: ctrl}
	mock.recorder = &MockGatewayUCMockRecorder{mock}
	return mock
}

// EXPECT returns an object that allows the caller to indicate expected use.
func (m *MockGatewayUC) EXPECT() *MockGatewayUCMockRecorder {
	return m.recorder
}

// ConfirmMatch mocks base method.
func (m *MockGatewayUC) ConfirmMatch(arg0 context.Context, arg1 *match.MatchConfirmRequest) (*match.MatchProposal, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "ConfirmMatch", arg0, arg1)
	ret0, _ := ret[0].(*match.MatchProposal)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// ConfirmMatch indicates an expected call of ConfirmMatch.
func (mr *MockGatewayUCMockRecorder) ConfirmMatch(arg0, arg1 interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "ConfirmMatch", reflect.TypeOf((*MockGatewayUC)(nil).ConfirmMatch), arg0, arg1)
}

// ProcessPayment mocks base method.
func (m *MockGatewayUC) ProcessPayment(arg0 context.Context, arg1 *ride.PaymentProccessRequest) (*ride.Payment, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "ProcessPayment", arg0, arg1)
	ret0, _ := ret[0].(*ride.Payment)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// ProcessPayment indicates an expected call of ProcessPayment.
func (mr *MockGatewayUCMockRecorder) ProcessPayment(arg0, arg1 interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "ProcessPayment", reflect.TypeOf((*MockGatewayUC)(nil).ProcessPayment), arg0, arg1)
}

// ProxyToLocationService mocks base method.
func (m *MockGatewayUC) ProxyToLocationService(arg0 context.Context, arg1, arg2 string, arg3 interface{}, arg4, arg5 map[string]string) (*core.ProxyResponse, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "ProxyToLocationService", arg0, arg1, arg2, arg3, arg4, arg5)
	ret0, _ := ret[0].(*core.ProxyResponse)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// ProxyToLocationService indicates an expected call of ProxyToLocationService.
func (mr *MockGatewayUCMockRecorder) ProxyToLocationService(arg0, arg1, arg2, arg3, arg4, arg5 interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "ProxyToLocationService", reflect.TypeOf((*MockGatewayUC)(nil).ProxyToLocationService), arg0, arg1, arg2, arg3, arg4, arg5)
}

// ProxyToMatchService mocks base method.
func (m *MockGatewayUC) ProxyToMatchService(arg0 context.Context, arg1, arg2 string, arg3 interface{}, arg4, arg5 map[string]string) (*core.ProxyResponse, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "ProxyToMatchService", arg0, arg1, arg2, arg3, arg4, arg5)
	ret0, _ := ret[0].(*core.ProxyResponse)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// ProxyToMatchService indicates an expected call of ProxyToMatchService.
func (mr *MockGatewayUCMockRecorder) ProxyToMatchService(arg0, arg1, arg2, arg3, arg4, arg5 interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "ProxyToMatchService", reflect.TypeOf((*MockGatewayUC)(nil).ProxyToMatchService), arg0, arg1, arg2, arg3, arg4, arg5)
}

// ProxyToRidesService mocks base method.
func (m *MockGatewayUC) ProxyToRidesService(arg0 context.Context, arg1, arg2 string, arg3 interface{}, arg4, arg5 map[string]string) (*core.ProxyResponse, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "ProxyToRidesService", arg0, arg1, arg2, arg3, arg4, arg5)
	ret0, _ := ret[0].(*core.ProxyResponse)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// ProxyToRidesService indicates an expected call of ProxyToRidesService.
func (mr *MockGatewayUCMockRecorder) ProxyToRidesService(arg0, arg1, arg2, arg3, arg4, arg5 interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "ProxyToRidesService", reflect.TypeOf((*MockGatewayUC)(nil).ProxyToRidesService), arg0, arg1, arg2, arg3, arg4, arg5)
}

// ProxyToUsersService mocks base method.
func (m *MockGatewayUC) ProxyToUsersService(arg0 context.Context, arg1, arg2 string, arg3 interface{}, arg4, arg5 map[string]string) (*core.ProxyResponse, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "ProxyToUsersService", arg0, arg1, arg2, arg3, arg4, arg5)
	ret0, _ := ret[0].(*core.ProxyResponse)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// ProxyToUsersService indicates an expected call of ProxyToUsersService.
func (mr *MockGatewayUCMockRecorder) ProxyToUsersService(arg0, arg1, arg2, arg3, arg4, arg5 interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "ProxyToUsersService", reflect.TypeOf((*MockGatewayUC)(nil).ProxyToUsersService), arg0, arg1, arg2, arg3, arg4, arg5)
}

// RideArrived mocks base method.
func (m *MockGatewayUC) RideArrived(arg0 context.Context, arg1 *ride.RideArrivalReq) (*ride.PaymentRequest, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "RideArrived", arg0, arg1)
	ret0, _ := ret[0].(*ride.PaymentRequest)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// RideArrived indicates an expected call of RideArrived.
func (mr *MockGatewayUCMockRecorder) RideArrived(arg0, arg1 interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "RideArrived", reflect.TypeOf((*MockGatewayUC)(nil).RideArrived), arg0, arg1)
}

// RideStart mocks base method.
func (m *MockGatewayUC) RideStart(arg0 context.Context, arg1 *ride.RideStartRequest) (*ride.Ride, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "RideStart", arg0, arg1)
	ret0, _ := ret[0].(*ride.Ride)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// RideStart indicates an expected call of RideStart.
func (mr *MockGatewayUCMockRecorder) RideStart(arg0, arg1 interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "RideStart", reflect.TypeOf((*MockGatewayUC)(nil).RideStart), arg0, arg1)
}

// UpdateBeaconStatus mocks base method.
func (m *MockGatewayUC) UpdateBeaconStatus(arg0 context.Context, arg1 *core.BeaconRequest) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "UpdateBeaconStatus", arg0, arg1)
	ret0, _ := ret[0].(error)
	return ret0
}

// UpdateBeaconStatus indicates an expected call of UpdateBeaconStatus.
func (mr *MockGatewayUCMockRecorder) UpdateBeaconStatus(arg0, arg1 interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "UpdateBeaconStatus", reflect.TypeOf((*MockGatewayUC)(nil).UpdateBeaconStatus), arg0, arg1)
}

// UpdateFinderStatus mocks base method.
func (m *MockGatewayUC) UpdateFinderStatus(arg0 context.Context, arg1 *core.FinderRequest) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "UpdateFinderStatus", arg0, arg1)
	ret0, _ := ret[0].(error)
	return ret0
}

// UpdateFinderStatus indicates an expected call of UpdateFinderStatus.
func (mr *MockGatewayUCMockRecorder) UpdateFinderStatus(arg0, arg1 interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "UpdateFinderStatus", reflect.TypeOf((*MockGatewayUC)(nil).UpdateFinderStatus), arg0, arg1)
}

// UpdateUserLocation mocks base method.
func (m *MockGatewayUC) UpdateUserLocation(arg0 context.Context, arg1 *location.LocationUpdate) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "UpdateUserLocation", arg0, arg1)
	ret0, _ := ret[0].(error)
	return ret0
}

// UpdateUserLocation indicates an expected call of UpdateUserLocation.
func (mr *MockGatewayUCMockRecorder) UpdateUserLocation(arg0, arg1 interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "UpdateUserLocation", reflect.TypeOf((*MockGatewayUC)(nil).UpdateUserLocation), arg0, arg1)
}
