# NebengJek Prometheus Configuration

# Global configuration
global:
  scrape_interval: 15s     # Set the scrape interval to every 15 seconds
  evaluation_interval: 15s # Evaluate rules every 15 seconds
  scrape_timeout: 10s      # Timeout before considering a scrape to be failed

# Alertmanager configuration
alerting:
  alertmanagers:
  - static_configs:
    - targets:
      # - alertmanager:9093

# Load rules once and periodically evaluate them
rule_files:
  # - "first_rules.yml"
  # - "second_rules.yml"

# Scrape configuration containing endpoints to scrape
scrape_configs:
  # Self monitoring
  - job_name: 'prometheus'
    static_configs:
      - targets: ['localhost:9090']

  # User Service monitoring
  - job_name: 'user-service'
    metrics_path: '/metrics'
    scrape_interval: 10s
    static_configs:
      - targets: ['user-service:9995']
    relabel_configs:
      - source_labels: [__address__]
        regex: '.*'
        target_label: instance
        replacement: 'user-service'

  # Location Service monitoring
  - job_name: 'location-service'
    metrics_path: '/metrics'
    scrape_interval: 10s
    static_configs:
      - targets: ['location-service:9998']
    relabel_configs:
      - source_labels: [__address__]
        regex: '.*'
        target_label: instance
        replacement: 'location-service'

  # Match Service monitoring
  - job_name: 'match-service'
    metrics_path: '/metrics'
    scrape_interval: 10s
    static_configs:
      - targets: ['match-service:10000']
    relabel_configs:
      - source_labels: [__address__]
        regex: '.*'
        target_label: instance
        replacement: 'match-service'

  # Rides Service monitoring
  - job_name: 'rides-service'
    metrics_path: '/metrics'
    scrape_interval: 10s
    static_configs:
      - targets: ['rides-service:10002']
    relabel_configs:
      - source_labels: [__address__]
        regex: '.*'
        target_label: instance
        replacement: 'rides-service'

  # Nginx/API Gateway monitoring
  - job_name: 'nginx'
    metrics_path: '/metrics'
    scrape_interval: 10s
    static_configs:
      - targets: ['api-gateway:9113']
    relabel_configs:
      - source_labels: [__address__]
        regex: '.*'
        target_label: instance
        replacement: 'api-gateway'

  # NATS monitoring
  - job_name: 'nats'
    metrics_path: '/metrics'
    scheme: http
    static_configs:
      - targets: ['nats:8222']
    metrics_path: '/varz'
    params:
      format: ['prometheus']

  # Redis monitoring
  - job_name: 'redis'
    static_configs:
      - targets: ['redis-exporter:9121']

  # PostgreSQL monitoring
  - job_name: 'postgres'
    static_configs:
      - targets: ['postgres-exporter:9187']

  # Node Exporter - System metrics
  - job_name: 'node'
    static_configs:
      - targets: ['node-exporter:9100']
      
  # Docker containers monitoring
  - job_name: 'cadvisor'
    scrape_interval: 5s
    static_configs:
      - targets: ['cadvisor:8080']