server:
  address: ":3001"

db:
  host: "postgres"
  port: 5432
  name: "nebengjek"
  user: "postgres"
  password: "postgres"

newrelic:
  app_name: "nebengjek-auth-service"
  license_key: "your-new-relic-license-key"

nsq:
  address: "nsqd:4150"
  lookupd_address: "nsqlookupd:4161"

jwt:
  secret: "your-jwt-secret-key"
  expiry: 24h