// Code generated by MockGen. DO NOT EDIT.
// Source: /Users/pirescerullo/GitHub/assessment/nebengjek/internal/pkg/models/websocket.go

// Package repositorymocks is a generated GoMock package.
package repositorymocks

import (
	context "context"
	reflect "reflect"
	time "time"

	gomock "github.com/golang/mock/gomock"
	"github.com/piresc/nebengjek/internal/pkg/models"
)

// MockWSConnectionRegistry is a mock of WSConnectionRegistry interface.
type MockWSConnectionRegistry struct {
	ctrl     *gomock.Controller
	recorder *MockWSConnectionRegistryMockRecorder
}

// MockWSConnectionRegistryMockRecorder is the mock recorder for MockWSConnectionRegistry.
type MockWSConnectionRegistryMockRecorder struct {
	mock *MockWSConnectionRegistry
}

// NewMockWSConnectionRegistry creates a new mock instance.
func NewMockWSConnectionRegistry(ctrl *gomock.Controller) *MockWSConnectionRegistry {
	mock := &MockWSConnectionRegistry{ctrl: ctrl}
	mock.recorder = &MockWSConnectionRegistryMockRecorder{mock}
	return mock
}

// EXPECT returns an object that allows the caller to indicate expected use.
func (m *MockWSConnectionRegistry) EXPECT() *MockWSConnectionRegistryMockRecorder {
	return m.recorder
}

// GetConnectedUsers mocks base method.
func (m *MockWSConnectionRegistry) GetConnectedUsers(ctx context.Context) ([]string, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "GetConnectedUsers", ctx)
	ret0, _ := ret[0].([]string)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// GetConnectedUsers indicates an expected call of GetConnectedUsers.
func (mr *MockWSConnectionRegistryMockRecorder) GetConnectedUsers(ctx interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "GetConnectedUsers", reflect.TypeOf((*MockWSConnectionRegistry)(nil).GetConnectedUsers), ctx)
}

// GetConnection mocks base method.
func (m *MockWSConnectionRegistry) GetConnection(ctx context.Context, userID string) (*models.WSSessionData, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "GetConnection", ctx, userID)
	ret0, _ := ret[0].(*models.WSSessionData)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// GetConnection indicates an expected call of GetConnection.
func (mr *MockWSConnectionRegistryMockRecorder) GetConnection(ctx, userID interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "GetConnection", reflect.TypeOf((*MockWSConnectionRegistry)(nil).GetConnection), ctx, userID)
}

// GetConnectionCount mocks base method.
func (m *MockWSConnectionRegistry) GetConnectionCount(ctx context.Context) (int, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "GetConnectionCount", ctx)
	ret0, _ := ret[0].(int)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// GetConnectionCount indicates an expected call of GetConnectionCount.
func (mr *MockWSConnectionRegistryMockRecorder) GetConnectionCount(ctx interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "GetConnectionCount", reflect.TypeOf((*MockWSConnectionRegistry)(nil).GetConnectionCount), ctx)
}

// GetServerConnections mocks base method.
func (m *MockWSConnectionRegistry) GetServerConnections(ctx context.Context, serverID string) ([]string, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "GetServerConnections", ctx, serverID)
	ret0, _ := ret[0].([]string)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// GetServerConnections indicates an expected call of GetServerConnections.
func (mr *MockWSConnectionRegistryMockRecorder) GetServerConnections(ctx, serverID interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "GetServerConnections", reflect.TypeOf((*MockWSConnectionRegistry)(nil).GetServerConnections), ctx, serverID)
}

// IsUserConnected mocks base method.
func (m *MockWSConnectionRegistry) IsUserConnected(ctx context.Context, userID string) (bool, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "IsUserConnected", ctx, userID)
	ret0, _ := ret[0].(bool)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// IsUserConnected indicates an expected call of IsUserConnected.
func (mr *MockWSConnectionRegistryMockRecorder) IsUserConnected(ctx, userID interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "IsUserConnected", reflect.TypeOf((*MockWSConnectionRegistry)(nil).IsUserConnected), ctx, userID)
}

// RegisterConnection mocks base method.
func (m *MockWSConnectionRegistry) RegisterConnection(ctx context.Context, userID string, session *models.WSSessionData) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "RegisterConnection", ctx, userID, session)
	ret0, _ := ret[0].(error)
	return ret0
}

// RegisterConnection indicates an expected call of RegisterConnection.
func (mr *MockWSConnectionRegistryMockRecorder) RegisterConnection(ctx, userID, session interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "RegisterConnection", reflect.TypeOf((*MockWSConnectionRegistry)(nil).RegisterConnection), ctx, userID, session)
}

// UnregisterConnection mocks base method.
func (m *MockWSConnectionRegistry) UnregisterConnection(ctx context.Context, userID string) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "UnregisterConnection", ctx, userID)
	ret0, _ := ret[0].(error)
	return ret0
}

// UnregisterConnection indicates an expected call of UnregisterConnection.
func (mr *MockWSConnectionRegistryMockRecorder) UnregisterConnection(ctx, userID interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "UnregisterConnection", reflect.TypeOf((*MockWSConnectionRegistry)(nil).UnregisterConnection), ctx, userID)
}

// UpdateActivity mocks base method.
func (m *MockWSConnectionRegistry) UpdateActivity(ctx context.Context, userID string, activity time.Time) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "UpdateActivity", ctx, userID, activity)
	ret0, _ := ret[0].(error)
	return ret0
}

// UpdateActivity indicates an expected call of UpdateActivity.
func (mr *MockWSConnectionRegistryMockRecorder) UpdateActivity(ctx, userID, activity interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "UpdateActivity", reflect.TypeOf((*MockWSConnectionRegistry)(nil).UpdateActivity), ctx, userID, activity)
}

// UpdateHeartbeat mocks base method.
func (m *MockWSConnectionRegistry) UpdateHeartbeat(ctx context.Context, userID string, ping, pong time.Time, missed int) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "UpdateHeartbeat", ctx, userID, ping, pong, missed)
	ret0, _ := ret[0].(error)
	return ret0
}

// UpdateHeartbeat indicates an expected call of UpdateHeartbeat.
func (mr *MockWSConnectionRegistryMockRecorder) UpdateHeartbeat(ctx, userID, ping, pong, missed interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "UpdateHeartbeat", reflect.TypeOf((*MockWSConnectionRegistry)(nil).UpdateHeartbeat), ctx, userID, ping, pong, missed)
}
