// Code generated by MockGen. DO NOT EDIT.
// Source: github.com/piresc/nebengjek/services/location (interfaces: LocationUC)

// Package mocks is a generated GoMock package.
package mocks

import (
	context "context"
	reflect "reflect"

	gomock "github.com/golang/mock/gomock"
	models "github.com/piresc/nebengjek/internal/pkg/models"
)

// MockLocationUC is a mock of LocationUC interface.
type MockLocationUC struct {
	ctrl     *gomock.Controller
	recorder *MockLocationUCMockRecorder
}

// MockLocationUCMockRecorder is the mock recorder for MockLocationUC.
type MockLocationUCMockRecorder struct {
	mock *MockLocationUC
}

// NewMockLocationUC creates a new mock instance.
func NewMockLocationUC(ctrl *gomock.Controller) *MockLocationUC {
	mock := &MockLocationUC{ctrl: ctrl}
	mock.recorder = &MockLocationUCMockRecorder{mock}
	return mock
}

// EXPECT returns an object that allows the caller to indicate expected use.
func (m *MockLocationUC) EXPECT() *MockLocationUCMockRecorder {
	return m.recorder
}

// AddAvailableDriver mocks base method.
func (m *MockLocationUC) AddAvailableDriver(arg0 context.Context, arg1 string, arg2 *models.Location) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "AddAvailableDriver", arg0, arg1, arg2)
	ret0, _ := ret[0].(error)
	return ret0
}

// AddAvailableDriver indicates an expected call of AddAvailableDriver.
func (mr *MockLocationUCMockRecorder) AddAvailableDriver(arg0, arg1, arg2 interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "AddAvailableDriver", reflect.TypeOf((*MockLocationUC)(nil).AddAvailableDriver), arg0, arg1, arg2)
}

// AddAvailablePassenger mocks base method.
func (m *MockLocationUC) AddAvailablePassenger(arg0 context.Context, arg1 string, arg2 *models.Location) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "AddAvailablePassenger", arg0, arg1, arg2)
	ret0, _ := ret[0].(error)
	return ret0
}

// AddAvailablePassenger indicates an expected call of AddAvailablePassenger.
func (mr *MockLocationUCMockRecorder) AddAvailablePassenger(arg0, arg1, arg2 interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "AddAvailablePassenger", reflect.TypeOf((*MockLocationUC)(nil).AddAvailablePassenger), arg0, arg1, arg2)
}

// FindNearbyDrivers mocks base method.
func (m *MockLocationUC) FindNearbyDrivers(arg0 context.Context, arg1 *models.Location, arg2 float64) ([]*models.NearbyUser, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "FindNearbyDrivers", arg0, arg1, arg2)
	ret0, _ := ret[0].([]*models.NearbyUser)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// FindNearbyDrivers indicates an expected call of FindNearbyDrivers.
func (mr *MockLocationUCMockRecorder) FindNearbyDrivers(arg0, arg1, arg2 interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "FindNearbyDrivers", reflect.TypeOf((*MockLocationUC)(nil).FindNearbyDrivers), arg0, arg1, arg2)
}

// GetDriverLocation mocks base method.
func (m *MockLocationUC) GetDriverLocation(arg0 context.Context, arg1 string) (models.Location, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "GetDriverLocation", arg0, arg1)
	ret0, _ := ret[0].(models.Location)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// GetDriverLocation indicates an expected call of GetDriverLocation.
func (mr *MockLocationUCMockRecorder) GetDriverLocation(arg0, arg1 interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "GetDriverLocation", reflect.TypeOf((*MockLocationUC)(nil).GetDriverLocation), arg0, arg1)
}

// GetPassengerLocation mocks base method.
func (m *MockLocationUC) GetPassengerLocation(arg0 context.Context, arg1 string) (models.Location, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "GetPassengerLocation", arg0, arg1)
	ret0, _ := ret[0].(models.Location)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// GetPassengerLocation indicates an expected call of GetPassengerLocation.
func (mr *MockLocationUCMockRecorder) GetPassengerLocation(arg0, arg1 interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "GetPassengerLocation", reflect.TypeOf((*MockLocationUC)(nil).GetPassengerLocation), arg0, arg1)
}

// RemoveAvailableDriver mocks base method.
func (m *MockLocationUC) RemoveAvailableDriver(arg0 context.Context, arg1 string) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "RemoveAvailableDriver", arg0, arg1)
	ret0, _ := ret[0].(error)
	return ret0
}

// RemoveAvailableDriver indicates an expected call of RemoveAvailableDriver.
func (mr *MockLocationUCMockRecorder) RemoveAvailableDriver(arg0, arg1 interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "RemoveAvailableDriver", reflect.TypeOf((*MockLocationUC)(nil).RemoveAvailableDriver), arg0, arg1)
}

// RemoveAvailablePassenger mocks base method.
func (m *MockLocationUC) RemoveAvailablePassenger(arg0 context.Context, arg1 string) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "RemoveAvailablePassenger", arg0, arg1)
	ret0, _ := ret[0].(error)
	return ret0
}

// RemoveAvailablePassenger indicates an expected call of RemoveAvailablePassenger.
func (mr *MockLocationUCMockRecorder) RemoveAvailablePassenger(arg0, arg1 interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "RemoveAvailablePassenger", reflect.TypeOf((*MockLocationUC)(nil).RemoveAvailablePassenger), arg0, arg1)
}

// StoreLocation mocks base method.
func (m *MockLocationUC) StoreLocation(arg0 context.Context, arg1 models.LocationUpdate) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "StoreLocation", arg0, arg1)
	ret0, _ := ret[0].(error)
	return ret0
}

// StoreLocation indicates an expected call of StoreLocation.
func (mr *MockLocationUCMockRecorder) StoreLocation(arg0, arg1 interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "StoreLocation", reflect.TypeOf((*MockLocationUC)(nil).StoreLocation), arg0, arg1)
}
