name: Unit Tests

on:
  pull_request:
    branches: [ master ]
  push:
    branches: [ master ]

jobs:
  test:
    name: Run Unit Tests
    runs-on: ubuntu-latest
    
    services:
      # Setup Redis service container for location and match service tests
      redis:
        image: redis
        ports:
          - 6379:6379
        options: >-
          --health-cmd "redis-cli ping"
          --health-interval 10s
          --health-timeout 5s
          --health-retries 5
          
      # Setup NATS service container for messaging tests
      nats:
        image: nats:2.9.15
        ports:
          - 4222:4222

    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Set up Go
        uses: actions/setup-go@v4
        with:
          go-version: '1.23'
          cache: true

      - name: Install dependencies
        run: go mod download
          
      # Create a temporary test file to modify the hardcoded NATS URLs
      - name: Create test wrapper
        run: |
          cat > test_wrapper.sh << 'EOF'
          #!/bin/bash
          set -e

          # Replace hardcoded NATS URLs in test files
          find . -name "*_test.go" -type f -exec grep -l "testNatsURL" {} \; | while read file; do
            sed -i 's|var testNatsURL = "nats://127.0.0.1:8369"|var testNatsURL = "nats://localhost:4222"|g' "$file"
          done

          # Run the tests
          go test ./... -race -coverprofile=coverage.txt -covermode=atomic
          EOF
          
          chmod +x test_wrapper.sh

      - name: Run tests with coverage
        run: ./test_wrapper.sh
        
      - name: Upload coverage report
        uses: codecov/codecov-action@v3
        with:
          file: ./coverage.txt
          fail_ci_if_error: false